### ISSUE TITLE
Improved crafting table - ticking block entity

### ISSUE THREAD

**Issue by MrTubzy456** [M4thG33k/LittleInsignificantThings_1.9#2] opened 2016-05-14 14:18 UTC
http://pastebin.com/Giki0E4z

**Comment by M4thG33k** [comment] 2016-05-14 14:43
Crash happened reloading recipes; can't seem to replicate it. Will close the issue later if nobody is able to reproduce it.

**Comment by M4thG33k** [comment] 2016-06-13 19:42
I couldn't narrow down the reason for this, but we've already moved onto 1.9.4 in which I replaced this block, so this is obsolete.

**Closed as completed by M4thG33k** 2016-06-13 19:42 UTC
